apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-vts-virtual-host-config
  namespace: default
data:
  default.conf: |

    server {
        listen 80 default_server;
        listen [::]:80 default_server;

        server_name localhost;
        root /usr/share/nginx/html;
        index index.html index.php;

        access_log /var/log/nginx/access.log nginx-vts;
        error_log /var/log/nginx/error.log;

        location = /healthz {
            add_header Content-Type text/plain;
            return 200 'ok';
        }

        location /status {
            vhost_traffic_status_display;
            vhost_traffic_status_display_format html;
        }

        location / {
            try_files $uri $uri/ =404;
        }

    }
